FROM ubuntu:22.04

# Install dependencies
RUN apt-get update && apt-get install -y \
    bash \
    curl \
    dpkg-dev \
    gzip \
    jq \
    sed \
    tar \
    unzip \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean \
    curl -sL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash \
    curl -sL https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/bin/yq \
    && chmod +x /usr/bin/yq


