FROM ubuntu:22.04

# Install dependencies
RUN apt-get update && apt-get install -y \
        bash \
        curl \
        dpkg-dev \
        gnupg \
        gzip \
        jq \
        sed \
        skopeo \
        tar \
        unzip \
        wget \
    && wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | tee /usr/share/keyrings/trivy.gpg > /dev/null \
    && echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | tee -a /etc/apt/sources.list.d/trivy.list \
    && apt-get update && apt-get install -y trivy \ 
    && curl -sf https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash \
    && curl -sf https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/bin/yq \
    && chmod +x /usr/bin/yq \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean


